version: '2'
  
services:

  app:
#    build: .
    image: dalareo/discourse
    volumes:
      - assets:/usr/src/app/public/assets
      - uploads:/usr/src/app/public/uploads
      - backups:/usr/src/app/public/backups
    links:
      - postgres
      - redis
    environment:
      - DISCOURSE_SMTP_ADDRESS=mail.example.com
      - DISCOURSE_SMTP_PORT=25
      - DISCOURSE_SMTP_USER_NAME="noreply@example.com"
      - DISCOURSE_SMTP_PASSWORD=""
      - DISCOURSE_HOSTNAME=meta.examble.com
      - DISCOURSE_DEVELOPER_EMAILS=account@example.com
    ports:
     - "3000:3000"

  postgres:
    image: postgres:9.4.8
    environment:
      - POSTGRES_USER=discourse
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3
