version: '2'
  
services:

  app:
#    build: .
    image: indiehosters/discourse
    volumes:
      - ./data/assets:/usr/src/app/public/assets
      - ./data/uploads:/usr/src/app/public/uploads
      - ./data/backups:/usr/src/app/public/backups
    links:
      - postgres
      - redis
    env_file:
      - ./env
    environment:
      - DISCOURSE_SMTP_ADDRESS=mail
      - DISCOURSE_SMTP_PORT=1025
      - DISCOURSE_SMTP_USER_NAME="noreply@yourdomain.com"
      - DISCOURSE_SMTP_PASSWORD=""
      - DISCOURSE_HOSTNAME=meta.examble.com
      - DISCOURSE_DEVELOPER_EMAILS=account@yourdomain.com
    ports:
     - "3000:3000"

  postgres:
    image: postgres:9.4.8
    env_file:
      - ./env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:3
